import { StyleSheet } from 'react-native';
import Constants from 'expo-constants';

export default StyleSheet.create({
    // FLAT LIST CLASSES FROM TREMDGOL APP (Hero1)

    flatList: {
        flex: 1,
        //flexBasis: '20%',
        //flexShrink: 1,
        //marginVertical: 2,
        //flexGrow: 1,
        paddingHorizontal: 1,
        paddingTop: 0,
        //borderWidth: 1,
        //height:'23%',
        //elevation: 2,
        marginTop: 6,
        marginBottom: 5
    },

    flatListHidden: {
        flex: 1,
        padding: 12,
        // borderWidth: 1,
        // flexBasis:'50%',
        flexDirection: 'row',
        justifyContent: 'center',
        alignContent: 'center',
        alignItems: 'center',
        borderRadius: 11,
        backgroundColor: '#ececec',
        marginBottom: 3,
        marginTop: 3,
        marginHorizontal: 5,
        //elevation: 2
    },

    flatListItem: {
        // flex: 1,
        paddingHorizontal: 8,
        paddingBottom: 2,
        borderRadius: 7,
        width: '100%',
        marginBottom: 6,
        marginHorizontal: 1,
        marginTop: 0,
        flexDirection: 'row',
        justifyContent: 'space-between',
        // borderWidth: 1,
        alignSelf: 'center',
        //elevation: 11
    },

    flatListItemTitle: {
        // flex: 1,
        fontSize: 13,
        color: '#41414d',
        fontWeight: 'bold',
        marginTop: 2,
        elevation: 1,
        //borderWidth: 1,
    },

    flatListItemClock: {
        // flex: 1,
        textAlignVertical: 'center',
        fontSize: 13,
        padding: 2,
        color: '#73738d',
        fontWeight: 'bold',
        marginTop: 0,
        borderColor: 'black',
        borderRadius: 7,
        //borderWidth: 1,
        width: '30%',
        backgroundColor: '#fff',
        textAlign: 'center',
        elevation: 2
    },

    flatListItemClockLast5min: {
        // flex: 1,
        textAlignVertical: 'center',
        fontSize: 13,
        padding: 2,
        color: '#73738d',
        fontWeight: 'bold',
        marginTop: 0,
        borderColor: 'black',
        borderRadius: 7,
        //borderWidth: 1,
        width: '30%',
        backgroundColor: '#CCCCCC',
        textAlign: 'center',
        elevation: 4
    },

    flatListItemPace: {
        // flex: 1,
        textAlignVertical: 'center',
        fontSize: 18,
        padding: 1,
        color: '#73738d',
        fontWeight: 'bold',
        marginTop: 0,
        borderColor: 'black',
        borderRadius: 7,
        //borderWidth: 1,
        width: '16%',
        backgroundColor: '#fff',
        textAlign: 'center',
        elevation: 4
    },

    flatListMainItem: {
        // flex: 1,
        flexDirection: 'row',
        width: '46%',
        backgroundColor: '#fff',
        borderRadius: 7,
        elevation: 4,
        //borderWidth: 1
    },

    flatListItemDetailsHome: {
        // flex: 1,
        color: '#41414d',
        fontWeight: 'bold',
        marginTop: 0,
        //borderWidth: 1,
        borderColor: 'black',
        borderRadius: 7,
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        backgroundColor: '#fff',
        paddingHorizontal: 4,
        padding: 2,
        //elevation: 6
    },

    flatListItemDetailsAway: {
        // flex: 1,
        color: '#41414d',
        fontWeight: 'bold',
        marginTop: 0,
        // borderWidth: 1,
        borderColor: 'black',
        borderRadius: 7,
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        backgroundColor: '#fff',
        paddingHorizontal: 4,
        padding: 2,
        alignSelf: 'flex-start',
        //elevation: 6
    },

    flatListItemDetailsTextHome: {
        // flex: 1,
        padding: 1,
        paddingHorizontal: 3,
        marginTop: 1,
        marginBottom: 1,
        alignSelf: 'center',
        // color: '#737380',
        //borderWidth: 1,
        borderColor: '#73738d',
        //width:'45%',
        textAlign: 'center',
        backgroundColor: '#e02041',
        borderRadius: 8,
        color: 'yellow',
        alignContent: 'center',
        textAlignVertical: 'center',
        elevation: 4,
    },

    flatListItemDetailsTextAway: {
        // flex: 1,
        padding: 1,
        paddingHorizontal: 3,
        marginTop: 1,
        marginBottom: 1,
        //borderWidth: 1,
        borderColor: '#73738d',
        //width:'45%',
        textAlign: 'center',
        backgroundColor: '#e02041',
        borderRadius: 8,
        color: 'yellow',
        // alignContent: 'flex-end',
        //        alignItems: 'flex-end',
        alignSelf: 'center',
        textAlignVertical: 'center',
        elevation: 4,
    },

    flatListStatsMinsItemMinute: {
        // flex: 1,
        textAlignVertical: 'center',
        fontSize: 13,
        padding: 2,
        color: '#73738d',
        fontWeight: 'bold',
        marginTop: 0,
        borderColor: 'black',
        borderRadius: 7,
        //borderWidth: 1,
        width: '9%',
        backgroundColor: '#fff',
        textAlign: 'center',
        elevation: 4
    },

    flatListStatsMinsMainItem: {
        // flex: 1,
        flexDirection: 'row',
        width: '90%',
        backgroundColor: '#fff',
        borderRadius: 7,
        marginRight: 10,
        marginLeft: 5,
        justifyContent: 'center',
        elevation: 4,
        //borderWidth: 1
    },

    flatListStatsMinsItemText: {
        // flex: 1,
        width: '87%',
        fontSize: 10,
        marginHorizontal: 0,
        paddingHorizontal: 0,
        backgroundColor: '#FFF',
        borderRadius: 7,
        textAlign: 'center',
        textAlignVertical: 'center',
        //elevation: 2,
        //borderWidth: 1
    },

    flatListItemStatsMinsDetailsTextHome: {
        flexDirection: 'row',
        // flex: 1,
        padding: 1,
        paddingLeft: 2,
        paddingRight: 2,
        marginTop: 2,
        marginBottom: 4,
        alignSelf: 'center',
        alignContent: 'center',
        // color: '#737380',
        //borderWidth: 1,
        //width:'45%',
        textAlign: 'center',
        backgroundColor: '#FFF', // vermelho padrao = e02041
        borderRadius: 8,
        borderColor: 'blue',
        color: 'yellow',
        textAlignVertical: 'center',
    },

    flatListItemStatsMinsDetailsTextAway: {
        flexDirection: 'row',
        // flex: 1,
        padding: 1,
        paddingLeft: 2,
        paddingRight: 2,
        marginTop: 2,
        marginBottom: 4,
        //borderWidth: 1,
        //width:'45%',
        textAlign: 'center',
        backgroundColor: '#FFF', // vermelho padrao = e02041
        borderRadius: 8,
        borderColor: 'red',
        color: 'yellow',
        // alignContent: 'flex-end',
        //        alignItems: 'flex-end',
        alignSelf: 'center',
        textAlignVertical: 'center',
    },

    flatListTeamLogoSize: {
        //flex: 1,
        marginTop: 0,
        alignSelf: 'center',
        //borderWidth: 1,
        paddingHorizontal: 11,
    },
});